server:
  port: 8080


spring:
  application:
    name: api-gateway


security:
  jwt:
    token:
      secret-key: 5368566D597133743677397A24432646294A404D635166546A576E5A72347537



  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#          lowerCaseServiceId:true

      routes:
        - id: player-service
          uri: lb://PLAYER-SERVICE
          predicates:
            - Path=/api/v1/players/**
          filters: AuthenticationFilter


        - id: team-service
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/api/v1/teams/**
          filters: AuthenticationFilter


        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/auth/**



        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/api/v2/auth/**
          filters: AuthenticationFilter


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
